imports:
  - { resource: ./application.yaml }

services:
  Profiles.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Profiles.Shared.ConnectionManager']
