imports:
  - { resource: ./application.yaml }

services:
  Posts.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Posts.Shared.ConnectionManager']
