imports:
  - { resource: ./application.yaml }

services:
  Feeds.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Feeds.Shared.ConnectionManager']
