imports:
  - { resource: ./application.yaml }

services:
  Followers.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Followers.Shared.ConnectionManager']
